### PR TITLE
fix: fixed message padding and inline code rendering

### LINKED ISSUE #26: decrease padding for user messages
Image

feels a bit excessive, it should probably look more like the send button:

Image

### LINKED ISSUE #27: inline code shouldn't be rendered as block
the tutor renders ALL code as block elements, even ones that probably should be inline:

Image

in markdown, this is the difference between `hello` and 

    hello

we should render inline code as inline, not as block elements.

### PR DESCRIPTION
**Pull request by abhi-sathvika**
closes #26 
closes #27 

Adjusted Markdown.tsx to render inline code within the line instead of a block and reduced the user messages padding.

https://github.com/user-attachments/assets/62f8b728-d007-43ef-bdbb-64ffbcdca795

### CODE REVIEW

File: src/components/Markdown.tsx [hunk 1]
```diff
@@ -44,6 +44,19 @@ export default function Markdown({
       notebook.insertCodeBelowActiveCell &&
       (language || '').toLowerCase().startsWith('py');
 
+    const isSingleLine =
+      typeof codeString === 'string' &&
+      !codeString.includes('\n') &&
+      codeString.length <= 20;
```
Comment (SamLau95) [inline src/components/Markdown.tsx]: we should probably refactor the 20 magic variable into a constant with a short comment above explaining why 20 is a good cutoff

**Review by SamLau95 — APPROVED** [review]
looks way better, thanks for the fixes!

**Comment by SamLau95** [comment]
btw, feel free to merge yourself once the build passes (i already approved the PR)
